import {Poppins} from 'next/font/google'
import './globals.css'
import Navbar from '@/components/NavBar'
import Footer from '@/components/Utilities/Footer'

const poppins = Poppins({subsets: ['latin'], weight: "500"})

export const metadata = {
    title: 'GarnimeList',
    description: 'Generated by create next app'
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={`${poppins.className} bg-yellow-500`}>
                <Navbar/> {children}
                <Footer/>
            </body>
        </html>
    )
}
